#ifndef _CIIIDENTITY_IDL_
#define _CIIIDENTITY_IDL_


#include "ciIClientCallback.idl"
#include "epo.idl"

module epo{
  exception TransactionForbidden {};
  struct Credentials {
    string username;
    string password;
  };


  interface ciIIdentityManager
  {



    string login(in string username, in string password, in ciIClientCallback callback);

    string logout()
      raises(TransactionForbidden,ciError);
    Credentials getCredentials();
  };
};
#endif
